Adding support of multi directives
vkolgi/json-to-graphql-query pull request #33
Opened 2021-12-13 11:12 UTC by MorganDbs

Hello, 

We really enjoyed the lib but multi directives support was missing and we so the "TODO", so here it is :)

We also added test for this use case.

Hope this will be ok for you and make it available to everyone

2021-12-17 04:50 UTC, vkolgi requested changes
Thanks for submitting the PR to improve the repo. I have a minor suggestion, can you take a look.

2021-12-17 08:04 UTC, MorganDbs commented on src/jsonToGraphQLQuery.ts
> +                        );
Yes you are right, your's is better !
I just pushed the changes :)

2021-12-19 12:54 UTC, vkolgi commented on src/jsonToGraphQLQuery.ts
> +                        );
@MorganDbs One issue with my suggestion was that typescript complains of no whitespace between the colons. This is trivial but fails the npm run build. Can you please add a space between the colon here and commit?. `{[item[0]]:item[1]})}`. 
You can check if this works in local by running `npm run build`.

2021-12-20 08:04 UTC, MorganDbs commented on src/jsonToGraphQLQuery.ts
> +                        );
@vkolgi Done :)

2021-12-20 08:23 UTC, vkolgi approved these changes
The changes looks good.

2021-12-20 08:24 UTC, merged

2021-12-20 08:47 UTC, MorganDbs commented
> The changes looks good.

@vkolgi 

Thanks to you ! 
Any idea on when you'll release the new version ?

2021-12-20 11:08 UTC, vkolgi commented
@MorganDbs I will bump the minor version and release today.

2021-12-20 11:26 UTC, MorganDbs commented
@vkolgi that's quick ! Thanks a lot